FROM ubuntu:16.04


RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               gcc \
               postgresql-client \
               python3 \
               python3-dev \
               python3-pip \
               python3-setuptools \
               python3-wheel \
               libpq-dev \
               virtualenv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    \
    && ln -s python3 /usr/bin/python \
    && ln -s pip3 /usr/bin/pip


ENV PYTHONUNBUFFERED 1
ENV HOME /tmp

# Cache will be used by pip and virtualenv
ENV XDG_CACHE_HOME /app/.cache

# Build takes uid as an argument.  It should match with the UID of the
# user who is running the build and who will be executing the container.
# This ensures that files written to host volumes will have same owner
# as the person executing the container.
ARG uid


RUN useradd --uid $uid webdev
