FROM python:3
RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends libpq5 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
COPY files /
ENTRYPOINT ["/entrypoint-prod.sh"]
