FROM ubuntu:16.04

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               gcc \
               postgresql-client \
               python3 \
               python3-dev \
               python3-pip \
               python3-setuptools \
               python3-wheel \
               libpq-dev \
               virtualenv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV PYTHONUNBUFFERED 1
ENV HOME /tmp

# Build can be given uid as an argument.  It should match with the UID
# of the user who is running the build and who will be executing the
# container.  This ensures that files written to host volumes will
# have same owner as the person executing the container.
ARG uid

RUN useradd --uid $uid webdev
